### ISSUE TITLE
Content is not saved on new entries

### ISSUE THREAD

**Issue by pascalw** [acoustep/craft-easymde#2]
Hey @acoustep thanks for this plugin, it's exactly what I need.
I did run into one issue where the content in the easymde editor is not saved when the entry in craft is not saved yet. If I first save an empty draft and then edit, it works.

### Steps to reproduce

1. Create a easymde field in Craft. Make it required.
2. Create a new entry, fill in some markdown in the required field.
3. Hit save.
4. A validation error is triggered and the easymde field is empty.

I briefly looked into the code and am not sure why it wouldn't work when the entry is not yet persisted?

**Comment by pascalw** [comment]
Hm interestingly this happens on Firefox, but not on Chrome.

**Comment by acoustep** [comment]
Thanks @pascalw for the bug report - I’ll look into it!

**Comment by acoustep** [comment]
I have released a fix for this in 0.1.3 - can you try this and confirm if it's working for you @pascalw ?

**Comment by pascalw** [comment]
Yes that works thanks @acoustep :+1:
