### ISSUE TITLE
Create a post 

### ISSUE THREAD

**Issue by OleOldhoj** [acoustep/craft-easymde#4]
I have added the field to a channel 

and I try to create a new post in the channel 
https://prnt.sc/pt3r1t 

And I get the following error https://prnt.sc/pt3sm8

**Comment by acoustep** [comment]
Hi @OleOldhoj 

Thanks for reporting this, looks like the fix for the GUI installer broke the actual plugin.

If you update to 0.1.7 this should now be fixed
