### ISSUE TITLE
Update for Craft 4

### ISSUE THREAD

**Issue by animaux** [acoustep/craft-easymde#5]
Is there any chance to have a working copy for Craft 4 anytime soon? I tried on a local copy but to no avail …

**Comment by acoustep** [comment]
Hi @animaux ,

I've not had a chance to play around with Craft 4 yet, but I'd certainly like to update the plugin to support it. I don't have an ETA I'm afraid as I'm unsure what the process is for upgrading yet.

**Comment by animaux** [comment]
Many thanks for your reply! There’s the [regular guide](https://craftcms.com/docs/4.x/extend/updating-plugins.html), I guess most of the listed stuff doesn’t even apply to this extension.

**Comment by acoustep** [comment]
Thanks @animaux I've tried making the necessary changes and pushed it to an experiemental `Craft4` branch.

If you could test this out in a dev environment and let me know if it's working for you?

Something like this should work

```
composer require acoustep/craft-easymde:dev-Craft4
```

**Comment by animaux** [comment]
Many thanks!

Sorry, but I’m a composer noob. I can’t update Craft itselt due to it’s requirement of easymde. But then I can’t update easymde because it requires Craft 4.0.0 … how do I solve this?

**Comment by acoustep** [comment]
I think you need to do them at the same time. e.g.

Follow the upgrade instructions on the Craft Docs ( https://craftcms.com/docs/4.x/upgrade.html#preparing-for-the-upgrade )

When it asks you to put `"craftcms/cms": "^4.0.0"` in your `composer.json` file, you should also change craft-easymde in the file as well to `"acoustep/craft-easymde": "dev-Craft4"`.

**Comment by animaux** [comment]
Thanks. OK, problem is another extension that’s not ready yet. Will see how far I get and report `:)`

**Comment by animaux** [comment]
The extension seems to be working fine! 

My twig templates are exploding though `;)`

**Comment by animaux** [comment]
Dev-version runs fine so far. The only problem is it sometimes takes a while for the editor to load which might be because of the [externally hosted files](https://github.com/acoustep/craft-easymde/issues/6).
